[package]
name = "wasm_demo"
version = "0.1.0"
authors = ["rust-analyzer developers"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
dev = ["console_error_panic_hook"]

[dependencies]
console_error_panic_hook = { version = "0.1.6", optional = true }
instant = { version = "0.1", features = ["wasm-bindgen"] }
log = { version = "0.4.14", features = ["release_max_level_warn"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_repr = "0.1.7"
serde-wasm-bindgen = "0.2.0"
stacker = "0.1.14"
wasm-bindgen = "0.2.74"
wasm-bindgen-rayon = "1.0.3"
io-providers = "0.1.2"

ide = { version = "0.0.45", package = "ra_ap_ide" }
ide_db = { version = "0.0.45", package = "ra_ap_ide_db" }
base_db = { version = "0.0.45", package = "ra_ap_base_db" }
rust-analyzer = { version = "0.0.45", package = "ra_ap_rust-analyzer" }
cfg = { version = "0.0.45", package = "ra_ap_cfg" }

